### ISSUE TITLE
Make TAP thermal

### ISSUE THREAD

**Issue by dogrady2** [arfc/tap-msr#10]
The TAP reactor needs to be reconfigured such that it is a thermal spectrum. Additional moderator rods will be added to the core and enrichment will be decreased in order to compensate the added reactivity.

**Comment by dogrady2** [comment]
If we go as thermal as possible.

[TAP Spectrum comparison.pdf](https://github.com/arfc/tap-msr/files/3297261/TAP.Spectrum.comparison.pdf)

**Comment by dogrady2** [comment]
@andrewryh

**Comment by andrewryh** [comment]
Looks very thermal. I bet keff for this thermal configuration is huge...

**Comment by andrewryh** [comment]
@dogrady2 Push the geometry. I gonna play with that.

**Comment by dogrady2** [comment]
@andrewryh Can you review pull request #11 so we can close this
