### ISSUE TITLE
Reference fuel compositions and moderator configurations at key points of TAP MSR life

### ISSUE THREAD

**Issue by ajhlee** [arfc/tap-msr#14]
Introduction: Changing fuel salt composition and neutron spectrum of the TAP MSR could have an impact on the reactor behavior and performance (such as load following capabilities) over the reactor lifetime. To facilitate such investigation, it would be useful to have the reference fuel compositions (ideally Serpent 2 compatible) and moderator configurations at key points of the TAP MSR's 23 year lifetime. These fuel compositions and moderator configurations could then be used to generate cross section data to be used in simulations involving Moltres.

The key moderator configuration indices of the TAP MSR are:
1) 1st moderator configuration (347 moderator rods per quarter core), representing the BOL configuration.
2) 5th moderator configuration, approximately representing 1/4 lifetime.
3) 8th moderator configuration, approximately representing 1/2 lifetime.
4) 11th moderator configuration, approximately representing 3/4 lifetime.
5) 15th moderator configuration, representing the last moderator configuration at EOL.

For the fuel composition, it would be useful to have the fuel compositions just before the first sparging and just after the first sparging to enable the study of the effects of fission gas accumulation and removal. This would result in 2 fuel salt compositions per moderator configuration.

**Comment by andrewryh** [comment]
> For the fuel composition, it would be useful to have the fuel compositions just before the first sparging and just after the first sparging to enable the study of the effects of fission gas accumulation and removal. 

@ajhlee Could you please clarify what is "first sparging"? Do you mean fuel composition right at the t=0 after the moderator switch or 3 days (my depletion step in simulations) after the moderator switch?

**Comment by ajhlee** [comment]
@andrewryh 3 days after the moderator switch. [See the red (1) and (2) in the attached screenshot]
![Capture](https://user-images.githubusercontent.com/47551448/87984293-5d2c0c00-ca9f-11ea-9276-a55751b61705.PNG)

Thanks!

**Comment by andrewryh** [comment]
@ajhlee 
![rwOHuvM](https://user-images.githubusercontent.com/20629016/88305664-5f74ad00-cccf-11ea-807a-fd2ee2b457d6.png)

Please, check carefully PR before merging.
Make sure that is what you need. That documentation is clear, etc.

Do not merge in 30 seconds please
